# Data Exploration 03

You're working on an exhibit for a local museum called "The Titanic Disaster". They've asked you to analyze the passenger manifests and see if you can find any interesting information for the exhibit.

The museum curator is particularly interested in why some people might have been more likely to survive than others.

## Part 1: Import Pandas and load the data

Remember to import Pandas the conventional way. If you've forgotten how, you may want to review [Data Exploration 01](https://byui-cse.github.io/cse450-course/module-01/exploration-01.html).

The dataset for this exploration is stored at the following url:

[https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv)

There are lots of ways to load data into your workspace. The easiest way in this case is to [ask Pandas to do it for you](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html).

### Initial Data Analysis
Once you've loaded the data, it's a good idea to poke around a little bit to find out what you're dealing with.

Some questions you might ask include:

* What does the data look like?
* What kind of data is in each column?
* Do any of the columns have missing values?

In [34]:
# Part 1: Enter your code below to import Pandas according to the
# conventional method. Then load the dataset into a Pandas dataframe.

# Write any code needed to explore the data by seeing what the first few
# rows look like. Then display a technical summary of the data to determine
# the data types of each column, and which columns have missing data.

!pip install lets-plot

from lets_plot import *
LetsPlot.setup_html()

import pandas as pd
import seaborn as sns

titanic = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv')

titanic.head()

Requirement already satisfied: lets-plot in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: pypng in /usr/local/lib/python3.12/dist-packages (from lets-plot) (0.20220715.0)
Requirement already satisfied: palettable in /usr/local/lib/python3.12/dist-packages (from lets-plot) (3.3.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from lets-plot) (11.3.0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
titanic.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    object
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB

## Part 2: Initial Exploration

Using your visualization library of choice, let's first look at some features in isolation. Generate visualizations showing:

- A comparison of the total number of passengers who survived compared to those that died.
- A comparison of the total number of males compared to females
- A histogram showing the distribution of sibling/spouse counts
- A histogram showing the distribution of parent/child counts

In [46]:
# graphOne = sns.countplot(x='Survived', data=titanic)

graphOne = ggplot(data = titanic, mapping = aes(x = 'Survived')) + geom_histogram(color = "white")
graphOne

In [49]:
graphTwo = ggplot(data = titanic, mapping = aes(x = 'Sex', fill = "Sex")) + geom_histogram()
graphTwo

In [79]:
# graphTree = sns.histplot(titanic['SibSp'])

graphThree = ggplot(data = titanic, mapping = aes(x = 'SibSp', fill = "SibSp")) + geom_histogram(color = "white")
graphThree

In [80]:
# graphFour = sns.histplot(titanic['Parch'])

graphFour = ggplot(data = titanic, mapping = aes(x = 'Parch', fill = "Parch")) + geom_histogram()
graphFour

## Part 3: Pairwise Comparisons
Use your visualization library of choice to look at how the survival distribution varied across different groups.

- Choose some features that you think might have had some influence over the likelihood of a titanic passenger surviving.

- For each of those features, generate a chart for each feature showing the survival distributions when taking that feature into account

In [72]:
graphComparison = ggplot(data = titanic, mapping = aes(x = 'Sex', fill = 'Survived')) + geom_bar(position = 'dodge') +
labs(title = 'Survival Count by Sex', x = 'Sex', y = 'Count')
graphComparison

In [81]:
graphComparison = ggplot(data = titanic, mapping = aes(x = 'Age', fill = 'Survived')) + \
    geom_histogram(position = 'dodge', bins = 20, color = 'white') + \
    labs(title = 'Survival Distribution by Age', x = 'Age', y = 'Count')
graphComparison

## Part 4: Feature Engineering

The museum curator wonders if the passenger's rank and title might have anything to do with whether or not they survived. Since this information is embedded in their name, we'll use "feature engineering" to create two new columns:

- Title: The passenger's title
- Rank: A boolean (true/false) indicating if a passenger was someone of rank.

For the first new column, you'll need to find a way to [extract the title portion of their name](https://pandas.pydata.org/docs/getting_started/intro_tutorials/10_text_data.html). Be sure to clean up any whitespace or extra punctuation.

For the second new column, you'll need to first look at a summary of your list of titles and decide what exactly constitutes a title of rank. Will you include military and eccelsiastical titles? Once you've made your decision, create the second column.

You may want to review prior Data Explorations for tips on creating new columns and checking for lists of values.

In [96]:
# Enter the code needed to create the two new columns

titanic["Name"].str.lower()
titanic["Name"].str.split(",")
titanic["Title"] = titanic["Name"].str.split(".").str.get(0)
titanic["Title"]

titanic['Title'] = titanic['Name'].str.split(',').str.get(1).str.split('.').str.get(0).str.strip()
titanic['Title']

print(titanic['Title'].value_counts())

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [99]:
commonTitles = ['Master', 'Dr', 'Rev', 'Col', 'Mlle', 'Major', 'Capt', 'Jonkheer', 'the Countess']
titanic['Rank'] = ~titanic['Title'].isin(commonTitles)

titanic['Rank'].value_counts()

Rank
True     829
False     62
Name: count, dtype: int64

### Revisit Visualizations
Now that you have the new columns in place. Revisit the pairwise comparison plots to see if the new columns reveal any interesting relationships.

In [102]:
# Visualize survival distribution by Rank
graphRank = ggplot(data = titanic, mapping = aes(x = 'Rank', fill = 'Survived')) + \
    geom_bar(position = 'dodge') + \
    labs(title = 'Survival by Rank', x = 'Has Title of Rank', y = 'Count')
graphRank

## Part 5: Encoding

The museum has partnered with a data science group to build some interactive predicitive models using the titanic passenger data.

Many machine learning algorithms require categorical features to be **encoded** as numbers.

There are two approaches to this, label encoding (sometimes called factorization), and "one-hot" encoding.

### Label Encoding

Label encoding creates numeric labels for each categorical value. For example, imagine we have a feature in the data called `Pet` with these values for the first five rows: `['Dog', 'Cat', 'Dog', 'Dog', 'Bird']`.

We could create a new feature called `Pet_Encoded` where those values are represented as: `[0, 1, 0, 0, 2]`. Where `0 = Dog, 1 = Cat, and 2 = Bird`.

In pandas there are two common ways to label encode a feature:

#### Method 1: factorize()

First, we could pandas' [factorize() method](https://pandas.pydata.org/docs/reference/api/pandas.factorize.html). It takes the series you want to encode as an argument and returns a list of two items.

The first item is an array of encoded values. The second is the set of original values.


    # The factorize() method returns the new values and the originals in a list.
    # So the [0] at the end indicates we want only the new values.
    myData['Pet_Encoded'] = pd.factorize(myData['Pet'])[0]


#### Method 2: Category Data Type
Every column in a pandas dataframe is a certain datatype. Usually, pandas infers which datatype to use based on the values of the column. However, we can use the `astype()` method to convert a feature from one type to another.

If we first convert a feature to the `category` datatype, we can ask pandas to create a new column in the data frame based on the category codes:

    # Convert our column to the category type
    myData['Pet'] = myData['Pet'].astype('category')
    myData['Pet_Encoded'] = myData['Pet'].cat.codes


Whichever method we choose, our machine learning algorithm could use the new `Pet_Encoded` feature in place of the `Pet` feature.

In [103]:
# Create a new column in the dataset called "Sex_Encoded" containing the
# label encoded values of the "Sex" column

titanic['Sex_Encoded'] = pd.factorize(titanic['Sex'])[0]
titanic['Sex_Encoded']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex_Encoded, Length: 891, dtype: int64

### One-Hot Encoding

One problem with label encoding is that it can make a categorical variable appear as if it contains a quantitative relationship between its values.

In the example above, is Bird twice as important as Cat? Some algorithms might interpret those values that way.

One-Hot encoding avoids this problem by creating a new feature for each category. The value of the new feature is either `0` (is not this value) or `1` (is this value).

In pandas, we can use the [get_dummies()](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html) method to deal with this problem:

    myEncodedData = pd.get_dummies(myData, columns=['Pet'])

In the case of our `Pet` example, the new features created by `get_dummies()` would be:

| Pet_is_Dog | Pet_is_Cat | Pet_is_Bird |
|:----------:|:----------:|:-----------:|
|      1     |      0     |      0      |
|      0     |      1     |      0      |
|      1     |      0     |      0      |
|      1     |      0     |      0      |
|      0     |      0     |      1      |

Notice that for our data, if `Pet_is_Bird` = 0 and `Pet_is_Cat` = 0, we know that the pet has to be a dog. So the `Pet_is_Dog` column contains redundant information. When this happens, we say that our data contains a _multicollinearity_ problem.

To avoid this, we can tell `get_dummies()` that we want to get rid of one of the columns using the `drop_first` parameter:

    myEncodedData = pd.get_dummies(myData, columns=['Pet'], drop_first=True)

The main disadvantage to One-Hot encoding is that if the feature you're encoding has a lot of different values, it can result in a lot of extra features. This can sometimes lead to poor performance with some types of algorithms.

In [109]:
# Use the pandas get_dummies() method to one-hot encode the Embarked column.

titanic = pd.get_dummies(titanic, columns=['Embarked'], drop_first=True)
titanic.head()

KeyError: "None of [Index(['Embarked'], dtype='object')] are in the [columns]"

## Part 6: Conclusions

Based on your analysis, what interesting relationships did you find? Write three interesting facts the museum can use in their exhibit.

1.  **Gender Disparity in Survival**: A significant majority of women passengers survived compared to men. This suggests that the 'women and children first' protocol might have been largely followed during the rescue efforts.
2.  **Age and Survival**: The survival distribution by age indicates that younger passengers, especially children, had a better chance of survival than older individuals. There also appears to be a notable drop in survival rates for some age groups.
3.  **Impact of Social Status/Rank**: Passengers with titles indicating a higher social rank (or uncommon titles, as defined in our feature engineering) had a considerably higher survival rate than those without such titles. This implies that social standing might have influenced access to lifeboats or rescue priority.

## 🌟 Above and Beyond 🌟

1. There appears to be a lot of different variations of similar titles. (such as abbreviations for Miss and Mademoiselle).

   Scan through the different titles to see which titles can be consolidated, then use what you know about data manipulation to simplify the distribution.

   Once you've finished, check the visualizations again to see if that made any difference.

2. The museum curator has room for a couple of nice visualizations for the exhibit. Create additional visualizations that are suitable for public display.

In [113]:
nicerPlot = ggplot(data = titanic, mapping = aes(x = 'Sex', fill = 'Survived')) + \
    geom_bar(position = 'dodge', color = 'white', size = 0.5) + \
    scale_fill_manual(values = ['#e41a1c', '#377eb8'], labels = ['Died', 'Survived']) + \
    labs(title = 'Gender and Survival: A Stark Contrast', \
         subtitle = 'Comparison of passenger survival counts by sex', \
         x = 'Passenger Sex', \
         y = 'Number of Passengers', \
         fill = 'Outcome') + \
    theme_minimal() + \
    theme(plot_title = element_text(size = 18, face = 'bold'), \
          plot_subtitle = element_text(size = 12, color = 'grey'), \
          legend_position = 'bottom')
nicerPlot