<a href="https://colab.research.google.com/github/omora14/googCol/blob/main/notebooks/module01-assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction
This assignment will test how well you're able to perform various data science-related tasks.

Each Problem Group below will center around a particular dataset that you have worked with before.

To ensure you receive full credit for a question, make sure you demonstrate the appropriate pandas, altair, or other commands as requested in the provided code blocks.

You may find that some questions require multiple steps to fully answer. Others require some mental arithmetic in addition to pandas commands. Use your best judgment.

## Submission
Each problem group asks a series of questions. This assignment consists of two submissions:

1. After completing the questions below, open the Module 01 Assessment Quiz in Canvas and enter your answers to these questions there.

2. After completing and submitting the quiz, save this Colab notebook as a GitHub Gist (You'll need to create a GitHub account for this), by selecting `Save a copy as a GitHub Gist` from the `File` menu above.

    In Canvas, open the Module 01 Assessment GitHub Gist assignment and paste the GitHub Gist URL for this notebook. Then submit that assignment.

## Problem Group 1

For the questions in this group, you'll work with the Netflix Movies Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv)

### Question 1
Load the dataset into a Pandas data frame and determine what data type is used to store the `release_year` feature.

In [5]:
import pandas as pd

netflix = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv')
netflix.info()
netflix.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

The 'Dtype' for release_year is int64

### Question 2
Filter your dataset so it contains only `TV Shows`. How many of those TV Shows were rated `TV-Y7`?

In [2]:
netflixShows = netflix[netflix['type'] == 'TV Show']
netflixShows['rating'].value_counts()

rating
TV-MA       679
TV-14       660
TV-PG       269
TV-Y        102
TV-Y7       100
TV-G         69
TV-Y7-FV     68
NR           16
R             2
G             1
PG            1
Name: count, dtype: int64

There are 100 TV-Y7

### Question 3
Further filter your dataset so it only contains TV Shows released between the years 2000 and 2009 inclusive. How many of *those* shows were rated `TV-Y7`?

In [6]:
netflixShowTime = netflixShows[(netflixShows['release_year'] >= 2000) & (netflixShows['release_year'] <= 2009)]
netflixShowTime['rating'].value_counts()

rating
TV-14       52
TV-PG       22
TV-MA       13
TV-Y7-FV    11
NR           4
TV-G         4
TV-Y7        4
TV-Y         3
Name: count, dtype: int64

## Problem Group 2

For the questions in this group, you'll work with the Cereal Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv)

### Question 4
After importing the dataset into a pandas data frame, determine the median amount of `protein` in cereal brands manufactured by Kelloggs. (`mfr` code "K")

In [14]:
# I already import pandas earlier, but will do it again to follow instructions

import pandas as pd

cereal = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv')

cerealKellogs = cereal[cereal['mfr'] == 'K']
cerealKellogs.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,108.695652,2.652174,0.608696,174.782609,2.739130,15.130435,7.565217,103.043478,34.782609,2.347826,1.077826,0.796087,44.038462
std,22.218818,1.070628,0.838783,84.132988,3.193991,4.465060,4.500768,91.982448,25.826267,0.775107,0.154830,0.209778,14.457434
min,50.000000,1.000000,0.000000,0.000000,0.000000,7.000000,0.000000,20.000000,25.000000,1.000000,1.000000,0.330000,29.924285
25%,100.000000,2.000000,0.000000,132.500000,1.000000,12.000000,3.000000,35.000000,25.000000,2.000000,1.000000,0.670000,34.478442
50%,110.000000,3.000000,0.000000,170.000000,1.000000,15.000000,7.000000,60.000000,25.000000,3.000000,1.000000,0.750000,40.560159
75%,115.000000,3.000000,1.000000,225.000000,3.000000,19.000000,12.000000,145.000000,25.000000,3.000000,1.000000,1.000000,50.013484
max,160.000000,6.000000,3.000000,320.000000,14.000000,22.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.000000,93.704912

### Question 5
In order to comply with new government regulations, all cereals must now come with a "Healthiness" rating. This rating is calculated based on this formula:

    healthiness = (protein + fiber) / sugar

Create a new `healthiness` column populated with values based on the above formula.

Then, determine the median healthiness value for only General Mills cereals (`mfr` = "G"), rounded to two decimal places.

In [16]:
healthiness = (cereal['protein'] + cereal['fiber']) / cereal['sugars']
cereal['healthiness'] = healthiness

cerealGM = cereal[cereal['mfr'] == 'G']
cerealGM.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,healthiness
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,111.363636,2.318182,1.363636,200.454545,1.272727,14.727273,7.954545,85.227273,35.227273,2.136364,1.049091,0.875000,34.485852,0.902024
std,10.371873,1.129111,0.581087,44.021345,1.241421,3.347804,3.872704,45.682060,26.343756,0.833550,0.132446,0.240906,8.946704,1.667625
min,100.000000,1.000000,1.000000,140.000000,0.000000,10.500000,1.000000,25.000000,25.000000,1.000000,1.000000,0.500000,19.823573,0.076923
25%,110.000000,2.000000,1.000000,180.000000,0.000000,12.000000,3.750000,55.000000,25.000000,1.250000,1.000000,0.750000,27.963172,0.212500
50%,110.000000,2.000000,1.000000,200.000000,1.500000,14.250000,8.500000,80.000000,25.000000,2.000000,1.000000,0.875000,36.181877,0.475000
75%,110.000000,3.000000,2.000000,217.500000,2.000000,16.750000,10.000000,108.750000,25.000000,3.000000,1.000000,1.000000,39.587829,0.666667
max,140.000000,6.000000,3.000000,290.000000,4.000000,21.000000,14.000000,230.000000,100.000000,3.000000,1.500000,1.500000,51.592193,8.000000

## Problem Group 3

For the questions in this group, you'll work with the Titanic Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv)

### Question 6

After loading the dataset into a pandas DataFrame, create a new column called `NameGroup` that contains the first letter of the passenger's surname in lower case.

Note that in the dataset, passenger's names are provided in the `Name` column and are listed as:

    Surname, Given names

For example, if a passenger's `Name` is `Braund, Mr. Owen Harris`, the `NameGroup` column should contain the value `b`.

Then count how many passengers have a `NameGroup` value of `k`.

In [18]:
import pandas as pd

titanic = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
titanic['NameGroup'] = titanic['Name'].apply(lambda x: x.split(',')[0][0].lower())
countK = titanic[titanic['NameGroup'] == 'k'].shape[0]
countK

28